// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxsylrovbjxkqwmjaixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c3lscm92Ymp4a3F3bWphaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODg4NjcsImV4cCI6MjA2MzI2NDg2N30.H7uvLQpkP64jnVoznUL06imLv7cQkWA-H63RiHIy_wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);